import 'package:json_annotation/json_annotation.dart';

part 'client_event.g.dart';

/// Represents an event generated by the client, not yet acknowledged by the server.
@JsonSerializable()
class ClientEvent {
  /// Client-generated unique event ID (UUID recommended).
  final String clientEventId;

  /// Domain event type name.
  final String type;

  /// Arbitrary JSON content describing the mutation.
  final Map<String, dynamic> ? payload;

  final List<String> ? payloadManifest; 
  /// The time the event was created, in milliseconds since epoch.
  final int createdAt;

  ClientEvent({
    required this.clientEventId,
    required this.type,
      this.payload,
      this.payloadManifest,
    required this.createdAt,
  }) {
    if (payload != null && payload!.containsKey('facts')) {
      final facts = payload!['facts'];
      if (facts is List) {
        for (var fact in facts) {
          if (fact is Map && !fact.containsKey('subject')) {
            throw ArgumentError("Invalid payload.. $fact'");
          }
        }
      }
    }
  }

  /// Creates a new `ClientEvent` from a JSON map.
  factory ClientEvent.fromJson(Map<String, dynamic> json) =>
      _$ClientEventFromJson(json);

  /// Converts this `ClientEvent` to a JSON map.
  Map<String, dynamic> toJson() => _$ClientEventToJson(this);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClientEvent &&
          runtimeType == other.runtimeType &&
          clientEventId == other.clientEventId;

  @override
  int get hashCode => clientEventId.hashCode;
}